name: Daily News Digest

on:
  schedule:
    # 毎日午前9時（JST）に実行（UTC 0時）
    - cron: '0 0 * * *'
  # 手動実行も可能
  workflow_dispatch:

jobs:
  generate-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install feedparser jinja2 google-generativeai requests
        
    - name: Generate news digest
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python news_digest2.py
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: false
